/*
Blockmate

Blockmate API OpenAPI documentation

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package blockmate

import (
	"encoding/json"
)

// ConnectAccount405Response struct for ConnectAccount405Response
type ConnectAccount405Response struct {
	Detail *string `json:"detail,omitempty"`
}

// NewConnectAccount405Response instantiates a new ConnectAccount405Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewConnectAccount405Response() *ConnectAccount405Response {
	this := ConnectAccount405Response{}
	return &this
}

// NewConnectAccount405ResponseWithDefaults instantiates a new ConnectAccount405Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewConnectAccount405ResponseWithDefaults() *ConnectAccount405Response {
	this := ConnectAccount405Response{}
	return &this
}

// GetDetail returns the Detail field value if set, zero value otherwise.
func (o *ConnectAccount405Response) GetDetail() string {
	if o == nil || o.Detail == nil {
		var ret string
		return ret
	}
	return *o.Detail
}

// GetDetailOk returns a tuple with the Detail field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConnectAccount405Response) GetDetailOk() (*string, bool) {
	if o == nil || o.Detail == nil {
		return nil, false
	}
	return o.Detail, true
}

// HasDetail returns a boolean if a field has been set.
func (o *ConnectAccount405Response) HasDetail() bool {
	if o != nil && o.Detail != nil {
		return true
	}

	return false
}

// SetDetail gets a reference to the given string and assigns it to the Detail field.
func (o *ConnectAccount405Response) SetDetail(v string) {
	o.Detail = &v
}

func (o ConnectAccount405Response) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Detail != nil {
		toSerialize["detail"] = o.Detail
	}
	return json.Marshal(toSerialize)
}

type NullableConnectAccount405Response struct {
	value *ConnectAccount405Response
	isSet bool
}

func (v NullableConnectAccount405Response) Get() *ConnectAccount405Response {
	return v.value
}

func (v *NullableConnectAccount405Response) Set(val *ConnectAccount405Response) {
	v.value = val
	v.isSet = true
}

func (v NullableConnectAccount405Response) IsSet() bool {
	return v.isSet
}

func (v *NullableConnectAccount405Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableConnectAccount405Response(val *ConnectAccount405Response) *NullableConnectAccount405Response {
	return &NullableConnectAccount405Response{value: val, isSet: true}
}

func (v NullableConnectAccount405Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableConnectAccount405Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


