/*
Blockmate

Blockmate API OpenAPI documentation

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package blockmate

import (
	"encoding/json"
)

// GetAccountHint200Response struct for GetAccountHint200Response
type GetAccountHint200Response struct {
	Description string `json:"description"`
	Url string `json:"url"`
	Intro string `json:"intro"`
	Fields GetAccountHint200ResponseFields `json:"fields"`
	Oauth bool `json:"oauth"`
}

// NewGetAccountHint200Response instantiates a new GetAccountHint200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetAccountHint200Response(description string, url string, intro string, fields GetAccountHint200ResponseFields, oauth bool) *GetAccountHint200Response {
	this := GetAccountHint200Response{}
	this.Description = description
	this.Url = url
	this.Intro = intro
	this.Fields = fields
	this.Oauth = oauth
	return &this
}

// NewGetAccountHint200ResponseWithDefaults instantiates a new GetAccountHint200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetAccountHint200ResponseWithDefaults() *GetAccountHint200Response {
	this := GetAccountHint200Response{}
	return &this
}

// GetDescription returns the Description field value
func (o *GetAccountHint200Response) GetDescription() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Description
}

// GetDescriptionOk returns a tuple with the Description field value
// and a boolean to check if the value has been set.
func (o *GetAccountHint200Response) GetDescriptionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Description, true
}

// SetDescription sets field value
func (o *GetAccountHint200Response) SetDescription(v string) {
	o.Description = v
}

// GetUrl returns the Url field value
func (o *GetAccountHint200Response) GetUrl() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Url
}

// GetUrlOk returns a tuple with the Url field value
// and a boolean to check if the value has been set.
func (o *GetAccountHint200Response) GetUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Url, true
}

// SetUrl sets field value
func (o *GetAccountHint200Response) SetUrl(v string) {
	o.Url = v
}

// GetIntro returns the Intro field value
func (o *GetAccountHint200Response) GetIntro() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Intro
}

// GetIntroOk returns a tuple with the Intro field value
// and a boolean to check if the value has been set.
func (o *GetAccountHint200Response) GetIntroOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Intro, true
}

// SetIntro sets field value
func (o *GetAccountHint200Response) SetIntro(v string) {
	o.Intro = v
}

// GetFields returns the Fields field value
func (o *GetAccountHint200Response) GetFields() GetAccountHint200ResponseFields {
	if o == nil {
		var ret GetAccountHint200ResponseFields
		return ret
	}

	return o.Fields
}

// GetFieldsOk returns a tuple with the Fields field value
// and a boolean to check if the value has been set.
func (o *GetAccountHint200Response) GetFieldsOk() (*GetAccountHint200ResponseFields, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Fields, true
}

// SetFields sets field value
func (o *GetAccountHint200Response) SetFields(v GetAccountHint200ResponseFields) {
	o.Fields = v
}

// GetOauth returns the Oauth field value
func (o *GetAccountHint200Response) GetOauth() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Oauth
}

// GetOauthOk returns a tuple with the Oauth field value
// and a boolean to check if the value has been set.
func (o *GetAccountHint200Response) GetOauthOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Oauth, true
}

// SetOauth sets field value
func (o *GetAccountHint200Response) SetOauth(v bool) {
	o.Oauth = v
}

func (o GetAccountHint200Response) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["description"] = o.Description
	}
	if true {
		toSerialize["url"] = o.Url
	}
	if true {
		toSerialize["intro"] = o.Intro
	}
	if true {
		toSerialize["fields"] = o.Fields
	}
	if true {
		toSerialize["oauth"] = o.Oauth
	}
	return json.Marshal(toSerialize)
}

type NullableGetAccountHint200Response struct {
	value *GetAccountHint200Response
	isSet bool
}

func (v NullableGetAccountHint200Response) Get() *GetAccountHint200Response {
	return v.value
}

func (v *NullableGetAccountHint200Response) Set(val *GetAccountHint200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableGetAccountHint200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableGetAccountHint200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetAccountHint200Response(val *GetAccountHint200Response) *NullableGetAccountHint200Response {
	return &NullableGetAccountHint200Response{value: val, isSet: true}
}

func (v NullableGetAccountHint200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetAccountHint200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


