/*
Blockmate

Blockmate API OpenAPI documentation

API version: 0.0.2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package blockmate

import (
	"encoding/json"
)

// UserAPIAuthenticateProject200Response struct for UserAPIAuthenticateProject200Response
type UserAPIAuthenticateProject200Response struct {
	Token string `json:"token"`
}

// NewUserAPIAuthenticateProject200Response instantiates a new UserAPIAuthenticateProject200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUserAPIAuthenticateProject200Response(token string) *UserAPIAuthenticateProject200Response {
	this := UserAPIAuthenticateProject200Response{}
	this.Token = token
	return &this
}

// NewUserAPIAuthenticateProject200ResponseWithDefaults instantiates a new UserAPIAuthenticateProject200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUserAPIAuthenticateProject200ResponseWithDefaults() *UserAPIAuthenticateProject200Response {
	this := UserAPIAuthenticateProject200Response{}
	return &this
}

// GetToken returns the Token field value
func (o *UserAPIAuthenticateProject200Response) GetToken() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Token
}

// GetTokenOk returns a tuple with the Token field value
// and a boolean to check if the value has been set.
func (o *UserAPIAuthenticateProject200Response) GetTokenOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Token, true
}

// SetToken sets field value
func (o *UserAPIAuthenticateProject200Response) SetToken(v string) {
	o.Token = v
}

func (o UserAPIAuthenticateProject200Response) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["token"] = o.Token
	}
	return json.Marshal(toSerialize)
}

type NullableUserAPIAuthenticateProject200Response struct {
	value *UserAPIAuthenticateProject200Response
	isSet bool
}

func (v NullableUserAPIAuthenticateProject200Response) Get() *UserAPIAuthenticateProject200Response {
	return v.value
}

func (v *NullableUserAPIAuthenticateProject200Response) Set(val *UserAPIAuthenticateProject200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableUserAPIAuthenticateProject200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableUserAPIAuthenticateProject200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUserAPIAuthenticateProject200Response(val *UserAPIAuthenticateProject200Response) *NullableUserAPIAuthenticateProject200Response {
	return &NullableUserAPIAuthenticateProject200Response{value: val, isSet: true}
}

func (v NullableUserAPIAuthenticateProject200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUserAPIAuthenticateProject200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


