/*
Blockmate

Blockmate API OpenAPI documentation

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package blockmate

import (
	"encoding/json"
)

// AccountProviderHint Account provider hint containing info about what is needed to connect such an account
type AccountProviderHint struct {
	AccountName string `json:"account_name"`
	AccountType string `json:"account_type"`
	AccountUrl string `json:"account_url"`
	Description string `json:"description"`
	Url string `json:"url"`
	Intro *string `json:"intro,omitempty"`
	Fields AccountProviderHintFields `json:"fields"`
	Oauth bool `json:"oauth"`
}

// NewAccountProviderHint instantiates a new AccountProviderHint object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAccountProviderHint(accountName string, accountType string, accountUrl string, description string, url string, fields AccountProviderHintFields, oauth bool) *AccountProviderHint {
	this := AccountProviderHint{}
	this.AccountName = accountName
	this.AccountType = accountType
	this.AccountUrl = accountUrl
	this.Description = description
	this.Url = url
	this.Fields = fields
	this.Oauth = oauth
	return &this
}

// NewAccountProviderHintWithDefaults instantiates a new AccountProviderHint object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAccountProviderHintWithDefaults() *AccountProviderHint {
	this := AccountProviderHint{}
	return &this
}

// GetAccountName returns the AccountName field value
func (o *AccountProviderHint) GetAccountName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.AccountName
}

// GetAccountNameOk returns a tuple with the AccountName field value
// and a boolean to check if the value has been set.
func (o *AccountProviderHint) GetAccountNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AccountName, true
}

// SetAccountName sets field value
func (o *AccountProviderHint) SetAccountName(v string) {
	o.AccountName = v
}

// GetAccountType returns the AccountType field value
func (o *AccountProviderHint) GetAccountType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.AccountType
}

// GetAccountTypeOk returns a tuple with the AccountType field value
// and a boolean to check if the value has been set.
func (o *AccountProviderHint) GetAccountTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AccountType, true
}

// SetAccountType sets field value
func (o *AccountProviderHint) SetAccountType(v string) {
	o.AccountType = v
}

// GetAccountUrl returns the AccountUrl field value
func (o *AccountProviderHint) GetAccountUrl() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.AccountUrl
}

// GetAccountUrlOk returns a tuple with the AccountUrl field value
// and a boolean to check if the value has been set.
func (o *AccountProviderHint) GetAccountUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AccountUrl, true
}

// SetAccountUrl sets field value
func (o *AccountProviderHint) SetAccountUrl(v string) {
	o.AccountUrl = v
}

// GetDescription returns the Description field value
func (o *AccountProviderHint) GetDescription() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Description
}

// GetDescriptionOk returns a tuple with the Description field value
// and a boolean to check if the value has been set.
func (o *AccountProviderHint) GetDescriptionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Description, true
}

// SetDescription sets field value
func (o *AccountProviderHint) SetDescription(v string) {
	o.Description = v
}

// GetUrl returns the Url field value
func (o *AccountProviderHint) GetUrl() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Url
}

// GetUrlOk returns a tuple with the Url field value
// and a boolean to check if the value has been set.
func (o *AccountProviderHint) GetUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Url, true
}

// SetUrl sets field value
func (o *AccountProviderHint) SetUrl(v string) {
	o.Url = v
}

// GetIntro returns the Intro field value if set, zero value otherwise.
func (o *AccountProviderHint) GetIntro() string {
	if o == nil || o.Intro == nil {
		var ret string
		return ret
	}
	return *o.Intro
}

// GetIntroOk returns a tuple with the Intro field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AccountProviderHint) GetIntroOk() (*string, bool) {
	if o == nil || o.Intro == nil {
		return nil, false
	}
	return o.Intro, true
}

// HasIntro returns a boolean if a field has been set.
func (o *AccountProviderHint) HasIntro() bool {
	if o != nil && o.Intro != nil {
		return true
	}

	return false
}

// SetIntro gets a reference to the given string and assigns it to the Intro field.
func (o *AccountProviderHint) SetIntro(v string) {
	o.Intro = &v
}

// GetFields returns the Fields field value
func (o *AccountProviderHint) GetFields() AccountProviderHintFields {
	if o == nil {
		var ret AccountProviderHintFields
		return ret
	}

	return o.Fields
}

// GetFieldsOk returns a tuple with the Fields field value
// and a boolean to check if the value has been set.
func (o *AccountProviderHint) GetFieldsOk() (*AccountProviderHintFields, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Fields, true
}

// SetFields sets field value
func (o *AccountProviderHint) SetFields(v AccountProviderHintFields) {
	o.Fields = v
}

// GetOauth returns the Oauth field value
func (o *AccountProviderHint) GetOauth() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Oauth
}

// GetOauthOk returns a tuple with the Oauth field value
// and a boolean to check if the value has been set.
func (o *AccountProviderHint) GetOauthOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Oauth, true
}

// SetOauth sets field value
func (o *AccountProviderHint) SetOauth(v bool) {
	o.Oauth = v
}

func (o AccountProviderHint) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["account_name"] = o.AccountName
	}
	if true {
		toSerialize["account_type"] = o.AccountType
	}
	if true {
		toSerialize["account_url"] = o.AccountUrl
	}
	if true {
		toSerialize["description"] = o.Description
	}
	if true {
		toSerialize["url"] = o.Url
	}
	if o.Intro != nil {
		toSerialize["intro"] = o.Intro
	}
	if true {
		toSerialize["fields"] = o.Fields
	}
	if true {
		toSerialize["oauth"] = o.Oauth
	}
	return json.Marshal(toSerialize)
}

type NullableAccountProviderHint struct {
	value *AccountProviderHint
	isSet bool
}

func (v NullableAccountProviderHint) Get() *AccountProviderHint {
	return v.value
}

func (v *NullableAccountProviderHint) Set(val *AccountProviderHint) {
	v.value = val
	v.isSet = true
}

func (v NullableAccountProviderHint) IsSet() bool {
	return v.isSet
}

func (v *NullableAccountProviderHint) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAccountProviderHint(val *AccountProviderHint) *NullableAccountProviderHint {
	return &NullableAccountProviderHint{value: val, isSet: true}
}

func (v NullableAccountProviderHint) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAccountProviderHint) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


