/*
Blockmate

Blockmate API OpenAPI documentation

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package blockmate

import (
	"encoding/json"
)

// Transactions200Response struct for Transactions200Response
type Transactions200Response struct {
	Accounts []Transactions200ResponseAccountsInner `json:"accounts,omitempty"`
	Transactions []Transaction `json:"transactions"`
}

// NewTransactions200Response instantiates a new Transactions200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTransactions200Response(transactions []Transaction) *Transactions200Response {
	this := Transactions200Response{}
	this.Transactions = transactions
	return &this
}

// NewTransactions200ResponseWithDefaults instantiates a new Transactions200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTransactions200ResponseWithDefaults() *Transactions200Response {
	this := Transactions200Response{}
	return &this
}

// GetAccounts returns the Accounts field value if set, zero value otherwise.
func (o *Transactions200Response) GetAccounts() []Transactions200ResponseAccountsInner {
	if o == nil || o.Accounts == nil {
		var ret []Transactions200ResponseAccountsInner
		return ret
	}
	return o.Accounts
}

// GetAccountsOk returns a tuple with the Accounts field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Transactions200Response) GetAccountsOk() ([]Transactions200ResponseAccountsInner, bool) {
	if o == nil || o.Accounts == nil {
		return nil, false
	}
	return o.Accounts, true
}

// HasAccounts returns a boolean if a field has been set.
func (o *Transactions200Response) HasAccounts() bool {
	if o != nil && o.Accounts != nil {
		return true
	}

	return false
}

// SetAccounts gets a reference to the given []Transactions200ResponseAccountsInner and assigns it to the Accounts field.
func (o *Transactions200Response) SetAccounts(v []Transactions200ResponseAccountsInner) {
	o.Accounts = v
}

// GetTransactions returns the Transactions field value
func (o *Transactions200Response) GetTransactions() []Transaction {
	if o == nil {
		var ret []Transaction
		return ret
	}

	return o.Transactions
}

// GetTransactionsOk returns a tuple with the Transactions field value
// and a boolean to check if the value has been set.
func (o *Transactions200Response) GetTransactionsOk() ([]Transaction, bool) {
	if o == nil {
		return nil, false
	}
	return o.Transactions, true
}

// SetTransactions sets field value
func (o *Transactions200Response) SetTransactions(v []Transaction) {
	o.Transactions = v
}

func (o Transactions200Response) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Accounts != nil {
		toSerialize["accounts"] = o.Accounts
	}
	if true {
		toSerialize["transactions"] = o.Transactions
	}
	return json.Marshal(toSerialize)
}

type NullableTransactions200Response struct {
	value *Transactions200Response
	isSet bool
}

func (v NullableTransactions200Response) Get() *Transactions200Response {
	return v.value
}

func (v *NullableTransactions200Response) Set(val *Transactions200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableTransactions200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableTransactions200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTransactions200Response(val *Transactions200Response) *NullableTransactions200Response {
	return &NullableTransactions200Response{value: val, isSet: true}
}

func (v NullableTransactions200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTransactions200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


