/*
Blockmate

Blockmate API OpenAPI documentation

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package blockmate

import (
	"encoding/json"
)

// UserAPIAuthenticateProject400Response struct for UserAPIAuthenticateProject400Response
type UserAPIAuthenticateProject400Response struct {
	Message *string `json:"message,omitempty"`
}

// NewUserAPIAuthenticateProject400Response instantiates a new UserAPIAuthenticateProject400Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUserAPIAuthenticateProject400Response() *UserAPIAuthenticateProject400Response {
	this := UserAPIAuthenticateProject400Response{}
	return &this
}

// NewUserAPIAuthenticateProject400ResponseWithDefaults instantiates a new UserAPIAuthenticateProject400Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUserAPIAuthenticateProject400ResponseWithDefaults() *UserAPIAuthenticateProject400Response {
	this := UserAPIAuthenticateProject400Response{}
	return &this
}

// GetMessage returns the Message field value if set, zero value otherwise.
func (o *UserAPIAuthenticateProject400Response) GetMessage() string {
	if o == nil || o.Message == nil {
		var ret string
		return ret
	}
	return *o.Message
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UserAPIAuthenticateProject400Response) GetMessageOk() (*string, bool) {
	if o == nil || o.Message == nil {
		return nil, false
	}
	return o.Message, true
}

// HasMessage returns a boolean if a field has been set.
func (o *UserAPIAuthenticateProject400Response) HasMessage() bool {
	if o != nil && o.Message != nil {
		return true
	}

	return false
}

// SetMessage gets a reference to the given string and assigns it to the Message field.
func (o *UserAPIAuthenticateProject400Response) SetMessage(v string) {
	o.Message = &v
}

func (o UserAPIAuthenticateProject400Response) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Message != nil {
		toSerialize["message"] = o.Message
	}
	return json.Marshal(toSerialize)
}

type NullableUserAPIAuthenticateProject400Response struct {
	value *UserAPIAuthenticateProject400Response
	isSet bool
}

func (v NullableUserAPIAuthenticateProject400Response) Get() *UserAPIAuthenticateProject400Response {
	return v.value
}

func (v *NullableUserAPIAuthenticateProject400Response) Set(val *UserAPIAuthenticateProject400Response) {
	v.value = val
	v.isSet = true
}

func (v NullableUserAPIAuthenticateProject400Response) IsSet() bool {
	return v.isSet
}

func (v *NullableUserAPIAuthenticateProject400Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUserAPIAuthenticateProject400Response(val *UserAPIAuthenticateProject400Response) *NullableUserAPIAuthenticateProject400Response {
	return &NullableUserAPIAuthenticateProject400Response{value: val, isSet: true}
}

func (v NullableUserAPIAuthenticateProject400Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUserAPIAuthenticateProject400Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


