/*
Blockmate

Blockmate API OpenAPI documentation

API version: 0.0.2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package blockmate

import (
	"encoding/json"
)

// GetDomainFromAddress200ResponseMetadataAttributesInner struct for GetDomainFromAddress200ResponseMetadataAttributesInner
type GetDomainFromAddress200ResponseMetadataAttributesInner struct {
	DisplayType *string `json:"display_type,omitempty"`
	TraitType *string `json:"trait_type,omitempty"`
	Value *GetDomainFromAddress200ResponseMetadataAttributesInnerValue `json:"value,omitempty"`
}

// NewGetDomainFromAddress200ResponseMetadataAttributesInner instantiates a new GetDomainFromAddress200ResponseMetadataAttributesInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetDomainFromAddress200ResponseMetadataAttributesInner() *GetDomainFromAddress200ResponseMetadataAttributesInner {
	this := GetDomainFromAddress200ResponseMetadataAttributesInner{}
	return &this
}

// NewGetDomainFromAddress200ResponseMetadataAttributesInnerWithDefaults instantiates a new GetDomainFromAddress200ResponseMetadataAttributesInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetDomainFromAddress200ResponseMetadataAttributesInnerWithDefaults() *GetDomainFromAddress200ResponseMetadataAttributesInner {
	this := GetDomainFromAddress200ResponseMetadataAttributesInner{}
	return &this
}

// GetDisplayType returns the DisplayType field value if set, zero value otherwise.
func (o *GetDomainFromAddress200ResponseMetadataAttributesInner) GetDisplayType() string {
	if o == nil || o.DisplayType == nil {
		var ret string
		return ret
	}
	return *o.DisplayType
}

// GetDisplayTypeOk returns a tuple with the DisplayType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetDomainFromAddress200ResponseMetadataAttributesInner) GetDisplayTypeOk() (*string, bool) {
	if o == nil || o.DisplayType == nil {
		return nil, false
	}
	return o.DisplayType, true
}

// HasDisplayType returns a boolean if a field has been set.
func (o *GetDomainFromAddress200ResponseMetadataAttributesInner) HasDisplayType() bool {
	if o != nil && o.DisplayType != nil {
		return true
	}

	return false
}

// SetDisplayType gets a reference to the given string and assigns it to the DisplayType field.
func (o *GetDomainFromAddress200ResponseMetadataAttributesInner) SetDisplayType(v string) {
	o.DisplayType = &v
}

// GetTraitType returns the TraitType field value if set, zero value otherwise.
func (o *GetDomainFromAddress200ResponseMetadataAttributesInner) GetTraitType() string {
	if o == nil || o.TraitType == nil {
		var ret string
		return ret
	}
	return *o.TraitType
}

// GetTraitTypeOk returns a tuple with the TraitType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetDomainFromAddress200ResponseMetadataAttributesInner) GetTraitTypeOk() (*string, bool) {
	if o == nil || o.TraitType == nil {
		return nil, false
	}
	return o.TraitType, true
}

// HasTraitType returns a boolean if a field has been set.
func (o *GetDomainFromAddress200ResponseMetadataAttributesInner) HasTraitType() bool {
	if o != nil && o.TraitType != nil {
		return true
	}

	return false
}

// SetTraitType gets a reference to the given string and assigns it to the TraitType field.
func (o *GetDomainFromAddress200ResponseMetadataAttributesInner) SetTraitType(v string) {
	o.TraitType = &v
}

// GetValue returns the Value field value if set, zero value otherwise.
func (o *GetDomainFromAddress200ResponseMetadataAttributesInner) GetValue() GetDomainFromAddress200ResponseMetadataAttributesInnerValue {
	if o == nil || o.Value == nil {
		var ret GetDomainFromAddress200ResponseMetadataAttributesInnerValue
		return ret
	}
	return *o.Value
}

// GetValueOk returns a tuple with the Value field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetDomainFromAddress200ResponseMetadataAttributesInner) GetValueOk() (*GetDomainFromAddress200ResponseMetadataAttributesInnerValue, bool) {
	if o == nil || o.Value == nil {
		return nil, false
	}
	return o.Value, true
}

// HasValue returns a boolean if a field has been set.
func (o *GetDomainFromAddress200ResponseMetadataAttributesInner) HasValue() bool {
	if o != nil && o.Value != nil {
		return true
	}

	return false
}

// SetValue gets a reference to the given GetDomainFromAddress200ResponseMetadataAttributesInnerValue and assigns it to the Value field.
func (o *GetDomainFromAddress200ResponseMetadataAttributesInner) SetValue(v GetDomainFromAddress200ResponseMetadataAttributesInnerValue) {
	o.Value = &v
}

func (o GetDomainFromAddress200ResponseMetadataAttributesInner) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.DisplayType != nil {
		toSerialize["display_type"] = o.DisplayType
	}
	if o.TraitType != nil {
		toSerialize["trait_type"] = o.TraitType
	}
	if o.Value != nil {
		toSerialize["value"] = o.Value
	}
	return json.Marshal(toSerialize)
}

type NullableGetDomainFromAddress200ResponseMetadataAttributesInner struct {
	value *GetDomainFromAddress200ResponseMetadataAttributesInner
	isSet bool
}

func (v NullableGetDomainFromAddress200ResponseMetadataAttributesInner) Get() *GetDomainFromAddress200ResponseMetadataAttributesInner {
	return v.value
}

func (v *NullableGetDomainFromAddress200ResponseMetadataAttributesInner) Set(val *GetDomainFromAddress200ResponseMetadataAttributesInner) {
	v.value = val
	v.isSet = true
}

func (v NullableGetDomainFromAddress200ResponseMetadataAttributesInner) IsSet() bool {
	return v.isSet
}

func (v *NullableGetDomainFromAddress200ResponseMetadataAttributesInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetDomainFromAddress200ResponseMetadataAttributesInner(val *GetDomainFromAddress200ResponseMetadataAttributesInner) *NullableGetDomainFromAddress200ResponseMetadataAttributesInner {
	return &NullableGetDomainFromAddress200ResponseMetadataAttributesInner{value: val, isSet: true}
}

func (v NullableGetDomainFromAddress200ResponseMetadataAttributesInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetDomainFromAddress200ResponseMetadataAttributesInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


