/*
Blockmate

Blockmate API OpenAPI documentation

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package blockmate

import (
	"encoding/json"
)

// GetTransactionRiskScore200Response struct for GetTransactionRiskScore200Response
type GetTransactionRiskScore200Response struct {
	Address *string `json:"address,omitempty"`
	Risk *int32 `json:"risk,omitempty"`
}

// NewGetTransactionRiskScore200Response instantiates a new GetTransactionRiskScore200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetTransactionRiskScore200Response() *GetTransactionRiskScore200Response {
	this := GetTransactionRiskScore200Response{}
	return &this
}

// NewGetTransactionRiskScore200ResponseWithDefaults instantiates a new GetTransactionRiskScore200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetTransactionRiskScore200ResponseWithDefaults() *GetTransactionRiskScore200Response {
	this := GetTransactionRiskScore200Response{}
	return &this
}

// GetAddress returns the Address field value if set, zero value otherwise.
func (o *GetTransactionRiskScore200Response) GetAddress() string {
	if o == nil || o.Address == nil {
		var ret string
		return ret
	}
	return *o.Address
}

// GetAddressOk returns a tuple with the Address field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetTransactionRiskScore200Response) GetAddressOk() (*string, bool) {
	if o == nil || o.Address == nil {
		return nil, false
	}
	return o.Address, true
}

// HasAddress returns a boolean if a field has been set.
func (o *GetTransactionRiskScore200Response) HasAddress() bool {
	if o != nil && o.Address != nil {
		return true
	}

	return false
}

// SetAddress gets a reference to the given string and assigns it to the Address field.
func (o *GetTransactionRiskScore200Response) SetAddress(v string) {
	o.Address = &v
}

// GetRisk returns the Risk field value if set, zero value otherwise.
func (o *GetTransactionRiskScore200Response) GetRisk() int32 {
	if o == nil || o.Risk == nil {
		var ret int32
		return ret
	}
	return *o.Risk
}

// GetRiskOk returns a tuple with the Risk field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetTransactionRiskScore200Response) GetRiskOk() (*int32, bool) {
	if o == nil || o.Risk == nil {
		return nil, false
	}
	return o.Risk, true
}

// HasRisk returns a boolean if a field has been set.
func (o *GetTransactionRiskScore200Response) HasRisk() bool {
	if o != nil && o.Risk != nil {
		return true
	}

	return false
}

// SetRisk gets a reference to the given int32 and assigns it to the Risk field.
func (o *GetTransactionRiskScore200Response) SetRisk(v int32) {
	o.Risk = &v
}

func (o GetTransactionRiskScore200Response) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Address != nil {
		toSerialize["address"] = o.Address
	}
	if o.Risk != nil {
		toSerialize["risk"] = o.Risk
	}
	return json.Marshal(toSerialize)
}

type NullableGetTransactionRiskScore200Response struct {
	value *GetTransactionRiskScore200Response
	isSet bool
}

func (v NullableGetTransactionRiskScore200Response) Get() *GetTransactionRiskScore200Response {
	return v.value
}

func (v *NullableGetTransactionRiskScore200Response) Set(val *GetTransactionRiskScore200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableGetTransactionRiskScore200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableGetTransactionRiskScore200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetTransactionRiskScore200Response(val *GetTransactionRiskScore200Response) *NullableGetTransactionRiskScore200Response {
	return &NullableGetTransactionRiskScore200Response{value: val, isSet: true}
}

func (v NullableGetTransactionRiskScore200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetTransactionRiskScore200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


