/*
Blockmate

Blockmate API OpenAPI documentation

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package blockmate

import (
	"encoding/json"
)

// GetAddressNameInfo200Response struct for GetAddressNameInfo200Response
type GetAddressNameInfo200Response struct {
	Name *string `json:"name,omitempty"`
	Category *string `json:"category,omitempty"`
}

// NewGetAddressNameInfo200Response instantiates a new GetAddressNameInfo200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetAddressNameInfo200Response() *GetAddressNameInfo200Response {
	this := GetAddressNameInfo200Response{}
	return &this
}

// NewGetAddressNameInfo200ResponseWithDefaults instantiates a new GetAddressNameInfo200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetAddressNameInfo200ResponseWithDefaults() *GetAddressNameInfo200Response {
	this := GetAddressNameInfo200Response{}
	return &this
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *GetAddressNameInfo200Response) GetName() string {
	if o == nil || o.Name == nil {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetAddressNameInfo200Response) GetNameOk() (*string, bool) {
	if o == nil || o.Name == nil {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *GetAddressNameInfo200Response) HasName() bool {
	if o != nil && o.Name != nil {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *GetAddressNameInfo200Response) SetName(v string) {
	o.Name = &v
}

// GetCategory returns the Category field value if set, zero value otherwise.
func (o *GetAddressNameInfo200Response) GetCategory() string {
	if o == nil || o.Category == nil {
		var ret string
		return ret
	}
	return *o.Category
}

// GetCategoryOk returns a tuple with the Category field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetAddressNameInfo200Response) GetCategoryOk() (*string, bool) {
	if o == nil || o.Category == nil {
		return nil, false
	}
	return o.Category, true
}

// HasCategory returns a boolean if a field has been set.
func (o *GetAddressNameInfo200Response) HasCategory() bool {
	if o != nil && o.Category != nil {
		return true
	}

	return false
}

// SetCategory gets a reference to the given string and assigns it to the Category field.
func (o *GetAddressNameInfo200Response) SetCategory(v string) {
	o.Category = &v
}

func (o GetAddressNameInfo200Response) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Name != nil {
		toSerialize["name"] = o.Name
	}
	if o.Category != nil {
		toSerialize["category"] = o.Category
	}
	return json.Marshal(toSerialize)
}

type NullableGetAddressNameInfo200Response struct {
	value *GetAddressNameInfo200Response
	isSet bool
}

func (v NullableGetAddressNameInfo200Response) Get() *GetAddressNameInfo200Response {
	return v.value
}

func (v *NullableGetAddressNameInfo200Response) Set(val *GetAddressNameInfo200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableGetAddressNameInfo200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableGetAddressNameInfo200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetAddressNameInfo200Response(val *GetAddressNameInfo200Response) *NullableGetAddressNameInfo200Response {
	return &NullableGetAddressNameInfo200Response{value: val, isSet: true}
}

func (v NullableGetAddressNameInfo200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetAddressNameInfo200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


