/*
Blockmate

Blockmate API OpenAPI documentation

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package blockmate

import (
	"encoding/json"
)

// DeleteUser404Response struct for DeleteUser404Response
type DeleteUser404Response struct {
	Message *string `json:"message,omitempty"`
}

// NewDeleteUser404Response instantiates a new DeleteUser404Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDeleteUser404Response() *DeleteUser404Response {
	this := DeleteUser404Response{}
	return &this
}

// NewDeleteUser404ResponseWithDefaults instantiates a new DeleteUser404Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDeleteUser404ResponseWithDefaults() *DeleteUser404Response {
	this := DeleteUser404Response{}
	return &this
}

// GetMessage returns the Message field value if set, zero value otherwise.
func (o *DeleteUser404Response) GetMessage() string {
	if o == nil || o.Message == nil {
		var ret string
		return ret
	}
	return *o.Message
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeleteUser404Response) GetMessageOk() (*string, bool) {
	if o == nil || o.Message == nil {
		return nil, false
	}
	return o.Message, true
}

// HasMessage returns a boolean if a field has been set.
func (o *DeleteUser404Response) HasMessage() bool {
	if o != nil && o.Message != nil {
		return true
	}

	return false
}

// SetMessage gets a reference to the given string and assigns it to the Message field.
func (o *DeleteUser404Response) SetMessage(v string) {
	o.Message = &v
}

func (o DeleteUser404Response) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Message != nil {
		toSerialize["message"] = o.Message
	}
	return json.Marshal(toSerialize)
}

type NullableDeleteUser404Response struct {
	value *DeleteUser404Response
	isSet bool
}

func (v NullableDeleteUser404Response) Get() *DeleteUser404Response {
	return v.value
}

func (v *NullableDeleteUser404Response) Set(val *DeleteUser404Response) {
	v.value = val
	v.isSet = true
}

func (v NullableDeleteUser404Response) IsSet() bool {
	return v.isSet
}

func (v *NullableDeleteUser404Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDeleteUser404Response(val *DeleteUser404Response) *NullableDeleteUser404Response {
	return &NullableDeleteUser404Response{value: val, isSet: true}
}

func (v NullableDeleteUser404Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDeleteUser404Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


