/*
Blockmate

Blockmate API OpenAPI documentation

API version: 0.0.2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package blockmate

import (
	"encoding/json"
)

// OwnedNftContract Object - Contract for returned NFT
type OwnedNftContract struct {
	// String - Address of NFT contract.
	Address *string `json:"address,omitempty"`
}

// NewOwnedNftContract instantiates a new OwnedNftContract object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOwnedNftContract() *OwnedNftContract {
	this := OwnedNftContract{}
	return &this
}

// NewOwnedNftContractWithDefaults instantiates a new OwnedNftContract object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOwnedNftContractWithDefaults() *OwnedNftContract {
	this := OwnedNftContract{}
	return &this
}

// GetAddress returns the Address field value if set, zero value otherwise.
func (o *OwnedNftContract) GetAddress() string {
	if o == nil || o.Address == nil {
		var ret string
		return ret
	}
	return *o.Address
}

// GetAddressOk returns a tuple with the Address field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OwnedNftContract) GetAddressOk() (*string, bool) {
	if o == nil || o.Address == nil {
		return nil, false
	}
	return o.Address, true
}

// HasAddress returns a boolean if a field has been set.
func (o *OwnedNftContract) HasAddress() bool {
	if o != nil && o.Address != nil {
		return true
	}

	return false
}

// SetAddress gets a reference to the given string and assigns it to the Address field.
func (o *OwnedNftContract) SetAddress(v string) {
	o.Address = &v
}

func (o OwnedNftContract) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Address != nil {
		toSerialize["address"] = o.Address
	}
	return json.Marshal(toSerialize)
}

type NullableOwnedNftContract struct {
	value *OwnedNftContract
	isSet bool
}

func (v NullableOwnedNftContract) Get() *OwnedNftContract {
	return v.value
}

func (v *NullableOwnedNftContract) Set(val *OwnedNftContract) {
	v.value = val
	v.isSet = true
}

func (v NullableOwnedNftContract) IsSet() bool {
	return v.isSet
}

func (v *NullableOwnedNftContract) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOwnedNftContract(val *OwnedNftContract) *NullableOwnedNftContract {
	return &NullableOwnedNftContract{value: val, isSet: true}
}

func (v NullableOwnedNftContract) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOwnedNftContract) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


