/*
Blockmate

Blockmate API OpenAPI documentation

API version: 0.0.2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package blockmate

import (
	"encoding/json"
)

// GetAddressRiskScore200Response struct for GetAddressRiskScore200Response
type GetAddressRiskScore200Response struct {
	Address *string `json:"address,omitempty"`
	Risk *int32 `json:"risk,omitempty"`
}

// NewGetAddressRiskScore200Response instantiates a new GetAddressRiskScore200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetAddressRiskScore200Response() *GetAddressRiskScore200Response {
	this := GetAddressRiskScore200Response{}
	return &this
}

// NewGetAddressRiskScore200ResponseWithDefaults instantiates a new GetAddressRiskScore200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetAddressRiskScore200ResponseWithDefaults() *GetAddressRiskScore200Response {
	this := GetAddressRiskScore200Response{}
	return &this
}

// GetAddress returns the Address field value if set, zero value otherwise.
func (o *GetAddressRiskScore200Response) GetAddress() string {
	if o == nil || o.Address == nil {
		var ret string
		return ret
	}
	return *o.Address
}

// GetAddressOk returns a tuple with the Address field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetAddressRiskScore200Response) GetAddressOk() (*string, bool) {
	if o == nil || o.Address == nil {
		return nil, false
	}
	return o.Address, true
}

// HasAddress returns a boolean if a field has been set.
func (o *GetAddressRiskScore200Response) HasAddress() bool {
	if o != nil && o.Address != nil {
		return true
	}

	return false
}

// SetAddress gets a reference to the given string and assigns it to the Address field.
func (o *GetAddressRiskScore200Response) SetAddress(v string) {
	o.Address = &v
}

// GetRisk returns the Risk field value if set, zero value otherwise.
func (o *GetAddressRiskScore200Response) GetRisk() int32 {
	if o == nil || o.Risk == nil {
		var ret int32
		return ret
	}
	return *o.Risk
}

// GetRiskOk returns a tuple with the Risk field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetAddressRiskScore200Response) GetRiskOk() (*int32, bool) {
	if o == nil || o.Risk == nil {
		return nil, false
	}
	return o.Risk, true
}

// HasRisk returns a boolean if a field has been set.
func (o *GetAddressRiskScore200Response) HasRisk() bool {
	if o != nil && o.Risk != nil {
		return true
	}

	return false
}

// SetRisk gets a reference to the given int32 and assigns it to the Risk field.
func (o *GetAddressRiskScore200Response) SetRisk(v int32) {
	o.Risk = &v
}

func (o GetAddressRiskScore200Response) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Address != nil {
		toSerialize["address"] = o.Address
	}
	if o.Risk != nil {
		toSerialize["risk"] = o.Risk
	}
	return json.Marshal(toSerialize)
}

type NullableGetAddressRiskScore200Response struct {
	value *GetAddressRiskScore200Response
	isSet bool
}

func (v NullableGetAddressRiskScore200Response) Get() *GetAddressRiskScore200Response {
	return v.value
}

func (v *NullableGetAddressRiskScore200Response) Set(val *GetAddressRiskScore200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableGetAddressRiskScore200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableGetAddressRiskScore200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetAddressRiskScore200Response(val *GetAddressRiskScore200Response) *NullableGetAddressRiskScore200Response {
	return &NullableGetAddressRiskScore200Response{value: val, isSet: true}
}

func (v NullableGetAddressRiskScore200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetAddressRiskScore200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


