/*
Blockmate

Blockmate API OpenAPI documentation

API version: 0.0.2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package blockmate

import (
	"encoding/json"
)

// TransactionRiskReportDetailsValue struct for TransactionRiskReportDetailsValue
type TransactionRiskReportDetailsValue struct {
	OwnCategories []RiskReportCategory `json:"own_categories,omitempty"`
	SourceOfFundsCategories []RiskReportCategory `json:"source_of_funds_categories,omitempty"`
}

// NewTransactionRiskReportDetailsValue instantiates a new TransactionRiskReportDetailsValue object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTransactionRiskReportDetailsValue() *TransactionRiskReportDetailsValue {
	this := TransactionRiskReportDetailsValue{}
	return &this
}

// NewTransactionRiskReportDetailsValueWithDefaults instantiates a new TransactionRiskReportDetailsValue object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTransactionRiskReportDetailsValueWithDefaults() *TransactionRiskReportDetailsValue {
	this := TransactionRiskReportDetailsValue{}
	return &this
}

// GetOwnCategories returns the OwnCategories field value if set, zero value otherwise.
func (o *TransactionRiskReportDetailsValue) GetOwnCategories() []RiskReportCategory {
	if o == nil || o.OwnCategories == nil {
		var ret []RiskReportCategory
		return ret
	}
	return o.OwnCategories
}

// GetOwnCategoriesOk returns a tuple with the OwnCategories field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TransactionRiskReportDetailsValue) GetOwnCategoriesOk() ([]RiskReportCategory, bool) {
	if o == nil || o.OwnCategories == nil {
		return nil, false
	}
	return o.OwnCategories, true
}

// HasOwnCategories returns a boolean if a field has been set.
func (o *TransactionRiskReportDetailsValue) HasOwnCategories() bool {
	if o != nil && o.OwnCategories != nil {
		return true
	}

	return false
}

// SetOwnCategories gets a reference to the given []RiskReportCategory and assigns it to the OwnCategories field.
func (o *TransactionRiskReportDetailsValue) SetOwnCategories(v []RiskReportCategory) {
	o.OwnCategories = v
}

// GetSourceOfFundsCategories returns the SourceOfFundsCategories field value if set, zero value otherwise.
func (o *TransactionRiskReportDetailsValue) GetSourceOfFundsCategories() []RiskReportCategory {
	if o == nil || o.SourceOfFundsCategories == nil {
		var ret []RiskReportCategory
		return ret
	}
	return o.SourceOfFundsCategories
}

// GetSourceOfFundsCategoriesOk returns a tuple with the SourceOfFundsCategories field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TransactionRiskReportDetailsValue) GetSourceOfFundsCategoriesOk() ([]RiskReportCategory, bool) {
	if o == nil || o.SourceOfFundsCategories == nil {
		return nil, false
	}
	return o.SourceOfFundsCategories, true
}

// HasSourceOfFundsCategories returns a boolean if a field has been set.
func (o *TransactionRiskReportDetailsValue) HasSourceOfFundsCategories() bool {
	if o != nil && o.SourceOfFundsCategories != nil {
		return true
	}

	return false
}

// SetSourceOfFundsCategories gets a reference to the given []RiskReportCategory and assigns it to the SourceOfFundsCategories field.
func (o *TransactionRiskReportDetailsValue) SetSourceOfFundsCategories(v []RiskReportCategory) {
	o.SourceOfFundsCategories = v
}

func (o TransactionRiskReportDetailsValue) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.OwnCategories != nil {
		toSerialize["own_categories"] = o.OwnCategories
	}
	if o.SourceOfFundsCategories != nil {
		toSerialize["source_of_funds_categories"] = o.SourceOfFundsCategories
	}
	return json.Marshal(toSerialize)
}

type NullableTransactionRiskReportDetailsValue struct {
	value *TransactionRiskReportDetailsValue
	isSet bool
}

func (v NullableTransactionRiskReportDetailsValue) Get() *TransactionRiskReportDetailsValue {
	return v.value
}

func (v *NullableTransactionRiskReportDetailsValue) Set(val *TransactionRiskReportDetailsValue) {
	v.value = val
	v.isSet = true
}

func (v NullableTransactionRiskReportDetailsValue) IsSet() bool {
	return v.isSet
}

func (v *NullableTransactionRiskReportDetailsValue) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTransactionRiskReportDetailsValue(val *TransactionRiskReportDetailsValue) *NullableTransactionRiskReportDetailsValue {
	return &NullableTransactionRiskReportDetailsValue{value: val, isSet: true}
}

func (v NullableTransactionRiskReportDetailsValue) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTransactionRiskReportDetailsValue) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


