/*
Blockmate

Blockmate API OpenAPI documentation

API version: 0.0.2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package blockmate

import (
	"encoding/json"
)

// AccountProviderHintFields struct for AccountProviderHintFields
type AccountProviderHintFields struct {
	ApiKey *string `json:"api_key,omitempty"`
	ApiSecret *string `json:"api_secret,omitempty"`
	ApiPassphrase *string `json:"api_passphrase,omitempty"`
	Description *string `json:"description,omitempty"`
	Wallet *string `json:"wallet,omitempty"`
}

// NewAccountProviderHintFields instantiates a new AccountProviderHintFields object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAccountProviderHintFields() *AccountProviderHintFields {
	this := AccountProviderHintFields{}
	return &this
}

// NewAccountProviderHintFieldsWithDefaults instantiates a new AccountProviderHintFields object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAccountProviderHintFieldsWithDefaults() *AccountProviderHintFields {
	this := AccountProviderHintFields{}
	return &this
}

// GetApiKey returns the ApiKey field value if set, zero value otherwise.
func (o *AccountProviderHintFields) GetApiKey() string {
	if o == nil || o.ApiKey == nil {
		var ret string
		return ret
	}
	return *o.ApiKey
}

// GetApiKeyOk returns a tuple with the ApiKey field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AccountProviderHintFields) GetApiKeyOk() (*string, bool) {
	if o == nil || o.ApiKey == nil {
		return nil, false
	}
	return o.ApiKey, true
}

// HasApiKey returns a boolean if a field has been set.
func (o *AccountProviderHintFields) HasApiKey() bool {
	if o != nil && o.ApiKey != nil {
		return true
	}

	return false
}

// SetApiKey gets a reference to the given string and assigns it to the ApiKey field.
func (o *AccountProviderHintFields) SetApiKey(v string) {
	o.ApiKey = &v
}

// GetApiSecret returns the ApiSecret field value if set, zero value otherwise.
func (o *AccountProviderHintFields) GetApiSecret() string {
	if o == nil || o.ApiSecret == nil {
		var ret string
		return ret
	}
	return *o.ApiSecret
}

// GetApiSecretOk returns a tuple with the ApiSecret field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AccountProviderHintFields) GetApiSecretOk() (*string, bool) {
	if o == nil || o.ApiSecret == nil {
		return nil, false
	}
	return o.ApiSecret, true
}

// HasApiSecret returns a boolean if a field has been set.
func (o *AccountProviderHintFields) HasApiSecret() bool {
	if o != nil && o.ApiSecret != nil {
		return true
	}

	return false
}

// SetApiSecret gets a reference to the given string and assigns it to the ApiSecret field.
func (o *AccountProviderHintFields) SetApiSecret(v string) {
	o.ApiSecret = &v
}

// GetApiPassphrase returns the ApiPassphrase field value if set, zero value otherwise.
func (o *AccountProviderHintFields) GetApiPassphrase() string {
	if o == nil || o.ApiPassphrase == nil {
		var ret string
		return ret
	}
	return *o.ApiPassphrase
}

// GetApiPassphraseOk returns a tuple with the ApiPassphrase field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AccountProviderHintFields) GetApiPassphraseOk() (*string, bool) {
	if o == nil || o.ApiPassphrase == nil {
		return nil, false
	}
	return o.ApiPassphrase, true
}

// HasApiPassphrase returns a boolean if a field has been set.
func (o *AccountProviderHintFields) HasApiPassphrase() bool {
	if o != nil && o.ApiPassphrase != nil {
		return true
	}

	return false
}

// SetApiPassphrase gets a reference to the given string and assigns it to the ApiPassphrase field.
func (o *AccountProviderHintFields) SetApiPassphrase(v string) {
	o.ApiPassphrase = &v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *AccountProviderHintFields) GetDescription() string {
	if o == nil || o.Description == nil {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AccountProviderHintFields) GetDescriptionOk() (*string, bool) {
	if o == nil || o.Description == nil {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *AccountProviderHintFields) HasDescription() bool {
	if o != nil && o.Description != nil {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *AccountProviderHintFields) SetDescription(v string) {
	o.Description = &v
}

// GetWallet returns the Wallet field value if set, zero value otherwise.
func (o *AccountProviderHintFields) GetWallet() string {
	if o == nil || o.Wallet == nil {
		var ret string
		return ret
	}
	return *o.Wallet
}

// GetWalletOk returns a tuple with the Wallet field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AccountProviderHintFields) GetWalletOk() (*string, bool) {
	if o == nil || o.Wallet == nil {
		return nil, false
	}
	return o.Wallet, true
}

// HasWallet returns a boolean if a field has been set.
func (o *AccountProviderHintFields) HasWallet() bool {
	if o != nil && o.Wallet != nil {
		return true
	}

	return false
}

// SetWallet gets a reference to the given string and assigns it to the Wallet field.
func (o *AccountProviderHintFields) SetWallet(v string) {
	o.Wallet = &v
}

func (o AccountProviderHintFields) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.ApiKey != nil {
		toSerialize["api_key"] = o.ApiKey
	}
	if o.ApiSecret != nil {
		toSerialize["api_secret"] = o.ApiSecret
	}
	if o.ApiPassphrase != nil {
		toSerialize["api_passphrase"] = o.ApiPassphrase
	}
	if o.Description != nil {
		toSerialize["description"] = o.Description
	}
	if o.Wallet != nil {
		toSerialize["wallet"] = o.Wallet
	}
	return json.Marshal(toSerialize)
}

type NullableAccountProviderHintFields struct {
	value *AccountProviderHintFields
	isSet bool
}

func (v NullableAccountProviderHintFields) Get() *AccountProviderHintFields {
	return v.value
}

func (v *NullableAccountProviderHintFields) Set(val *AccountProviderHintFields) {
	v.value = val
	v.isSet = true
}

func (v NullableAccountProviderHintFields) IsSet() bool {
	return v.isSet
}

func (v *NullableAccountProviderHintFields) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAccountProviderHintFields(val *AccountProviderHintFields) *NullableAccountProviderHintFields {
	return &NullableAccountProviderHintFields{value: val, isSet: true}
}

func (v NullableAccountProviderHintFields) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAccountProviderHintFields) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


