/*
Blockmate

Blockmate API OpenAPI documentation

API version: 0.0.2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package blockmate

import (
	"encoding/json"
)

// DeleteUser200Response struct for DeleteUser200Response
type DeleteUser200Response struct {
	Message *string `json:"message,omitempty"`
}

// NewDeleteUser200Response instantiates a new DeleteUser200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDeleteUser200Response() *DeleteUser200Response {
	this := DeleteUser200Response{}
	return &this
}

// NewDeleteUser200ResponseWithDefaults instantiates a new DeleteUser200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDeleteUser200ResponseWithDefaults() *DeleteUser200Response {
	this := DeleteUser200Response{}
	return &this
}

// GetMessage returns the Message field value if set, zero value otherwise.
func (o *DeleteUser200Response) GetMessage() string {
	if o == nil || o.Message == nil {
		var ret string
		return ret
	}
	return *o.Message
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeleteUser200Response) GetMessageOk() (*string, bool) {
	if o == nil || o.Message == nil {
		return nil, false
	}
	return o.Message, true
}

// HasMessage returns a boolean if a field has been set.
func (o *DeleteUser200Response) HasMessage() bool {
	if o != nil && o.Message != nil {
		return true
	}

	return false
}

// SetMessage gets a reference to the given string and assigns it to the Message field.
func (o *DeleteUser200Response) SetMessage(v string) {
	o.Message = &v
}

func (o DeleteUser200Response) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Message != nil {
		toSerialize["message"] = o.Message
	}
	return json.Marshal(toSerialize)
}

type NullableDeleteUser200Response struct {
	value *DeleteUser200Response
	isSet bool
}

func (v NullableDeleteUser200Response) Get() *DeleteUser200Response {
	return v.value
}

func (v *NullableDeleteUser200Response) Set(val *DeleteUser200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableDeleteUser200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableDeleteUser200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDeleteUser200Response(val *DeleteUser200Response) *NullableDeleteUser200Response {
	return &NullableDeleteUser200Response{value: val, isSet: true}
}

func (v NullableDeleteUser200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDeleteUser200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


