/*
Blockmate

Blockmate API OpenAPI documentation

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package blockmate

import (
	"encoding/json"
)

// AuthUser200Response struct for AuthUser200Response
type AuthUser200Response struct {
	// UserJWT
	Token *string `json:"token,omitempty"`
}

// NewAuthUser200Response instantiates a new AuthUser200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAuthUser200Response() *AuthUser200Response {
	this := AuthUser200Response{}
	return &this
}

// NewAuthUser200ResponseWithDefaults instantiates a new AuthUser200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAuthUser200ResponseWithDefaults() *AuthUser200Response {
	this := AuthUser200Response{}
	return &this
}

// GetToken returns the Token field value if set, zero value otherwise.
func (o *AuthUser200Response) GetToken() string {
	if o == nil || o.Token == nil {
		var ret string
		return ret
	}
	return *o.Token
}

// GetTokenOk returns a tuple with the Token field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AuthUser200Response) GetTokenOk() (*string, bool) {
	if o == nil || o.Token == nil {
		return nil, false
	}
	return o.Token, true
}

// HasToken returns a boolean if a field has been set.
func (o *AuthUser200Response) HasToken() bool {
	if o != nil && o.Token != nil {
		return true
	}

	return false
}

// SetToken gets a reference to the given string and assigns it to the Token field.
func (o *AuthUser200Response) SetToken(v string) {
	o.Token = &v
}

func (o AuthUser200Response) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Token != nil {
		toSerialize["token"] = o.Token
	}
	return json.Marshal(toSerialize)
}

type NullableAuthUser200Response struct {
	value *AuthUser200Response
	isSet bool
}

func (v NullableAuthUser200Response) Get() *AuthUser200Response {
	return v.value
}

func (v *NullableAuthUser200Response) Set(val *AuthUser200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableAuthUser200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableAuthUser200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAuthUser200Response(val *AuthUser200Response) *NullableAuthUser200Response {
	return &NullableAuthUser200Response{value: val, isSet: true}
}

func (v NullableAuthUser200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAuthUser200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


